version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:latest
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - ingress_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adguard.rule=Host(`adguard.granbacken`)"
        - "traefik.http.routers.adguard.entrypoints=web"
        - "traefik.http.services.adguard.loadbalancer.server.port=80"
        - "traefik.http.services.adguard.loadbalancer.healthcheck.path=/login.html"
        - "traefik.http.services.adguard.loadbalancer.healthcheck.interval=10s"
        - "traefik.http.services.adguard.loadbalancer.healthcheck.timeout=10s"

volumes:
  adguard_work:
  adguard_conf:

networks:
  ingress_network:
    name: ingress_network
    external: true
