http:
  routers:
    dashboard:
      rule: "Host(`traefik.granbacken`)"
      service: "api@internal"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: /etc/traefik/certs/granbacken.crt
      keyFile: /etc/traefik/certs/granbacken.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/granbacken.crt
        keyFile: /etc/traefik/certs/granbacken.key

certificatesResolvers:
  letsencrypt:
    acme:
      email: "your-email@example.com"  # Replace with your email
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
