global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'adguard'
    static_configs:
      - targets: ['adguard_adguard:80']  # Matches service name, port 80 for web UI

  - job_name: 'traefik'
    static_configs:
      - targets: ['ingress_traefik:8080']  # Corrected typo, port 8080 for metrics
  - job_name: 'portainer'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['infra_portainer-agent:9001']  # Agent metrics on 8000
