version: '3.8'

services:
  vacuum:
    image: mediaserver:5000/vacuum:latest
    secrets:
      - source: xiaomi_username
        target: xiaomi_username
      - source: xiaomi_password
        target: xiaomi_password
    networks:
      - ingress_network
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.http.routers.vacuum.rule=Host(`vacuum.granbacken`)
        - traefik.http.routers.vacuum.entrypoints=web
        - traefik.http.services.vacuum.loadbalancer.server.port=5001
        - traefik.docker.network=ingress_network
      replicas: 2
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

  alarm_poller:
    image: mediaserver:5000/alarm_poller:latest
    secrets:
      - source: verisure_username
        target: verisure_username
      - source: verisure_password
        target: verisure_password
    networks:
      - ingress_network
    deploy:
      placement:
        constraints:
          - node.hostname == slave1
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m

secrets:
  verisure_username:
    external: true
    name: verisure_username
  verisure_password:
    external: true
    name: verisure_password
  xiaomi_username:
    external: true
    name: xiaomi_username
  xiaomi_password:
    external: true
    name: xiaomi_password

networks:
  ingress_network:
    external: true
