version: '3.8'

services:
  vacuum:
    image: mediaserver:5000/vacuum:latest
    networks:
      - ingress_network
    deploy:
      replicas: 2
      placement:
        constraints: [] # Allow on any node
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vacuum.rule=Host(`vacuum.granbacken`)"
        - "traefik.http.routers.vacuum.entrypoints=web,websecure"
        - "traefik.http.routers.vacuum.tls=true"
        - "traefik.http.services.vacuum.loadbalancer.server.port=5001"
        - "traefik.docker.network=ingress_network"
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    secrets:
      - xiaomi_username
      - xiaomi_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vacuum_plejd:
    image-arg: mediaserver:5000/vacuum:latest
    networks:
      - ingress_network
    deploy:
      replicas: 1
      placement:
        constraints: [] # Allow on any node
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vacuum-plejd.rule=Host(`vacuum.granbacken`) && PathPrefix(`/plejd`)"
        - "traefik.http.routers.vacuum-plejd.entrypoints=web,websecure"
        - "traefik.http.routers.vacuum-plejd.tls=true"
        - "traefik.http.services.vacuum-plejd.loadbalancer.server.port=5002"
        - "traefik.docker.network=ingress_network"
      resources:
        limits:
          memory: 64m
        reservations:
          memory: 32m
    secrets:
      - plejd_api_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "plejd_trigger.py"]

  nodered:
    image: mediaserver:5000/nodered:latest
    networks:
      - ingress_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == mediaserver] # Bluetooth on mediaserver
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodered.rule=Host(`vacuum.granbacken`) && PathPrefix(`/nodered`)"
        - "traefik.http.routers.nodered.entrypoints=web,websecure"
        - "traefik.http.routers.nodered.tls=true"
        - "traefik.http.services.nodered.loadbalancer.server.port=1880"
        - "traefik.docker.network=ingress_network"
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    volumes:
      - nodered_data:/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0  # Bluetooth adapter

volumes:
  nodered_data:

networks:
  ingress_network:
    external: true

secrets:
  xiaomi_username:
    external: true
  xiaomi_password:
    external: true
  plejd_api_key:
    external: true
