version: '3.8'

services:
  vacuum:
    image: mediaserver:5000/vacuum:latest
    networks:
      - ingress_network
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vacuum.rule=Host(`vacuum.granbacken`)"
        - "traefik.http.routers.vacuum.entrypoints=web,websecure"
        - "traefik.http.routers.vacuum.tls=true"
        - "traefik.http.services.vacuum.loadbalancer.server.port=5001"
        - "traefik.docker.network=ingress_network"
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    secrets:
     - xiaomi_username
     - xiaomi_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  ingress_network:
    external: true

secrets:
  xiaomi_username:
    external: true
  xiaomi_password:
    external: true
