version: "3.8"

services:
  vacuum:
    image: mediaserver:5000/vacuum:latest
    networks:
      - ingress_network
    deploy:
      replicas: 2
      placement: {}
      labels:
        - traefik.enable=true
        - traefik.http.routers.midarr.rule=Host(`vacuum.local`)
        - traefik.http.routers.midarr.entrypoints=web
        - traefik.http.services.midarr.loadbalancer.server.port=5001
        - traefik.docker.network=ingress_network
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    environment:
      XIAOMI_USERNAME_FILE: /run/secrets/xiaomi_username
      XIAOMI_PASSWORD_FILE: /run/secrets/xiaomi_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: xiaomi_username
        target: xiaomi_username
      - source: xiaomi_password
        target: xiaomi_password

  alarm_poller:
    image: mediaserver:5000/alarm_poller:latest
    networks:
      - ingress_network
    deploy:
      placement: {}
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      VERISURE_USERNAME_FILE: /run/secrets/verisure_username
      VERISURE_PASSWORD_FILE: /run/secrets/verisure_password
    secrets:
      - source: verisure_username
        target: verisure_username
      - source: verisure_password
        target: verisure_password

networks:
  ingress_network:
    external: true

secrets:
  xiaomi_username:
    external: true
  xiaomi_password:
    external: true
  verisure_username:
    external: true
  verisure_password:
    external: true
