version: '3.8'

services:
  vacuum:
    image: mediaserver:5000/vacuum:latest
    networks:
      - ingress_network
    deploy:
      replicas: 2
      placement:
        constraints: [] # Allow on any node
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vacuum.rule=Host(`vacuum.granbacken`)"
        - "traefik.http.routers.vacuum.entrypoints=web,websecure"
        - "traefik.http.routers.vacuum.tls=true"
        - "traefik.http.services.vacuum.loadbalancer.server.port=5001"
        - "traefik.docker.network=ingress_network"
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m
    secrets:
      - xiaomi_username
      - xiaomi_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  alarm_poller:
    image: mediaserver:5000/alarm_poller:latest
    networks:
      - ingress_network
    deploy:
      replicas: 1
      placement:
        constraints: [] # Allow on any node
      labels:
        - "traefik.enable=false"
      resources:
        limits:
          memory: 64m
        reservations:
          memory: 32m
    secrets:
      - verisure_username
      - verisure_password

networks:
  ingress_network:
    external: true

secrets:
  xiaomi_username:
    external: true
  xiaomi_password:
    external: true
  verisure_username:
    external: true
  verisure_password:
    external: true
