global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only expose services with explicit labels
    swarmMode: true         # Enable Swarm integration

api:
  dashboard: true
  insecure: true  # For testing; secure this in production with secrets

log:
  level: DEBUG

core:
  defaultRuleSyntax: v2
